services:
  superset:
    build:
      context: .
      target: dev
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app"]
    restart: unless-stopped
    ports:
      - 8088:8088
    user: root
    volumes:
      - ./docker:/app/docker
      - ./superset:/app/superset
      - superset_home:/app/superset_home
    env_file:
      - path: docker/.env
        required: true
volumes:
  superset_home:
    external: false